/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: teddyp (https://sketchfab.com/teddyp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tpc-gt1-aed05c299cf74d4cb0626dc40974b5e2
Title: TPC GT1
*/

import * as THREE from 'three'
import React, { JSX, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube_0: THREE.Mesh
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube_3: THREE.Mesh
    Cube007_0: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cube007_3: THREE.Mesh
    Cube007_4: THREE.Mesh
    Cube007_5: THREE.Mesh
    Cube007_6: THREE.Mesh
    Cube007_7: THREE.Mesh
    Cube007_8: THREE.Mesh
    Cube007_9: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cylinder_3: THREE.Mesh
    Cylinder_4: THREE.Mesh
    Cube001_0: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube002_0: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube003_0: THREE.Mesh
    Torus_0: THREE.Mesh
  }
  materials: {
    car_paint: THREE.MeshStandardMaterial
    black_01: THREE.MeshStandardMaterial
    black_03: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    black_02: THREE.MeshStandardMaterial
    window: THREE.MeshStandardMaterial
    side_mirrors: THREE.MeshStandardMaterial
    lights: THREE.MeshStandardMaterial
    orange_lights: THREE.MeshStandardMaterial
    low_light: THREE.MeshStandardMaterial
    wite: THREE.MeshStandardMaterial
    rubber: THREE.MeshStandardMaterial
    wheel: THREE.MeshStandardMaterial
    disk: THREE.MeshStandardMaterial
    front_light_cover: THREE.MeshStandardMaterial
    back_light_cover: THREE.MeshStandardMaterial
    grill_01: THREE.MeshStandardMaterial
    grill_02: THREE.MeshStandardMaterial
  }
}

export function Car_1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/elements/car-1/scene.gltf') as unknown as GLTFResult
  const carRef = useRef<THREE.Group>(null);



  return (
    <group {...props} ref={carRef} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.549}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_0.geometry}
          material={materials.car_paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.black_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.black_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_0.geometry}
          material={materials.black_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_3.geometry}
          material={materials.black_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_4.geometry}
          material={materials.side_mirrors}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_5.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_6.geometry}
          material={materials.orange_lights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_7.geometry}
          material={materials.low_light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_8.geometry}
          material={materials.wite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_9.geometry}
          material={materials.car_paint}
        />
        <mesh
       
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0.geometry}
          material={materials.rubber}
        />
        <mesh
       
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials.wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3.geometry}
          material={materials.car_paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={materials.disk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_0.geometry}
          material={materials.front_light_cover}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.back_light_cover}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_0.geometry}
          material={materials.grill_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials.grill_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_0.geometry}
          material={materials.grill_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus_0.geometry}
          material={materials.black_03}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/elements/car-1/scene.gltf')
