"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CAPTAAINR (https://sketchfab.com/CAPTAAINR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-lanterntexturedrigged-89362a83a6834d068d05ee5c7589cf33
Title: Green Lantern(Textured)(Rigged)
*/

import * as THREE from "three";
import React, { JSX, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    GreenLantern_D: THREE.MeshStandardMaterial;
  };
};

type ActionName = "IDLE001" | "IDLE002" | "IDLE001_1" | "IDLE003";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Green_Lantern(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);

  const { nodes, materials, animations } = useGLTF(
    "/elements/green-latern/scene.gltf",
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (!actions) return;

    const action = actions["IDLE002"];

    if (action) {
      action.reset().fadeIn(0.3).play();
    }
  }, [actions]);
  /* const { actions } = useAnimations<GLTFActions>(animations, group) */
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="f73295e7564349bfa8be78014d700d96fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="GreenLantern">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials.GreenLantern_D}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <group name="Object_7" rotation={[-Math.PI / 2, 0, 0]} />
                    <group
                      name="greenlantern_n"
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <group name="Movement" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/elements/green-latern/scene.gltf");
