"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ole Gunnar Isager (https://sketchfab.com/FrenchBaguette)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-cln-r-school-project-9a793a9293fb4ec89936aebfda8fc434
Title: Robot CLN-R (School Project)
*/

import * as THREE from 'three'
import React, { JSX, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    pCube43_lambert4_0: THREE.Mesh
    pCube43_MetalShiny_0: THREE.Mesh
    pCube43_Rubber_0: THREE.Mesh
    pCube43_Metal_0: THREE.Mesh
    pCube43_lambert1_0: THREE.Mesh
    pCube43_pasted__Eyes_0: THREE.Mesh
    pCube43_BlackGlass_0: THREE.Mesh
  }
  materials: {
    lambert4: THREE.MeshStandardMaterial
    MetalShiny: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    pasted__Eyes: THREE.MeshStandardMaterial
    BlackGlass: THREE.MeshStandardMaterial
  }
}

export function Robot_1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/elements/robot-1/robot-1.gltf') as unknown as GLTFResult

   const ref = useRef<THREE.Group>(null!)

  useFrame((state, delta) => {
    if (!ref.current) return

    // slow rotation
    ref.current.rotation.y += delta * 0.6

    // floating up/down
    ref.current.position.y = Math.sin(state.clock.elapsedTime) * 0.2
  })
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_lambert4_0.geometry}
        material={materials.lambert4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_MetalShiny_0.geometry}
        material={materials.MetalShiny}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_Rubber_0.geometry}
        material={materials.Rubber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_Metal_0.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_pasted__Eyes_0.geometry}
        material={materials.pasted__Eyes}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_BlackGlass_0.geometry}
        material={materials.BlackGlass}
      />
    </group>
  )
}

useGLTF.preload('/elements/robot-1/robot-1.gltf')
